apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsuser-deployment
  labels:
    app: eventsuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventsuser
  template:
    metadata:
      labels:
        app: eventsuser
    spec:
      containers:
      - name: eventsuser
        image: khalilmilan91/mevent_user:s2
        ports:
        - containerPort: 9003
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: EVENTS_USER_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: eventsuser
spec:
  selector:
    app: eventsuser
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003