apiVersion: apps/v1
kind: Deployment
metadata:
  name: forums-deployment
  labels:
    app: forums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forums
  template:
    metadata:
      labels:
        app: forums
    spec:
      containers:
      - name: forums
        image: khalilmilan91/mforum:s2
        ports:
        - containerPort: 9005
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: FORUM_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: forums
spec:
  selector:
    app: forums
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005