apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectsusers-deployment
  labels:
    app: projectsusers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectsusers
  template:
    metadata:
      labels:
        app: projectsusers
    spec:
      containers:
      - name: projectsusers
        image: khalilmilan91/mproject-user:s2
        ports:
        - containerPort: 9038
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: PROJECTS_USER_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: projectsusers
spec:
  selector:
    app: projectsusers
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9038
      targetPort: 9038