apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdevice-deployment
  labels:
    app: usersdevice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersdevice
  template:
    metadata:
      labels:
        app: usersdevice
    spec:
      containers:
      - name: usersdevice
        image: khalilmilan91/m_user_device:s2
        ports:
        - containerPort: 9022
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: USERS_DEVICE_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: usersdevice
spec:
  selector:
    app: usersdevice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9022
      targetPort: 9022