apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-deployment
  labels:
    app: votes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votes
  template:
    metadata:
      labels:
        app: votes
    spec:
      containers:
      - name: users
        image: khalilmilan91/mvote:s2
        ports:
        - containerPort: 9011
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: VOTES_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: votes
spec:
  selector:
    app: votes
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9011
      targetPort: 9011