apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-deployment
  labels:
    app: groups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groups
  template:
    metadata:
      labels:
        app: groups
    spec:
      containers:
      - name: users
        image: khalilmilan91/mgroupe:s2
        ports:
        - containerPort: 9008
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: GROUPS_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: groups
spec:
  selector:
    app: groups
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9008
      targetPort: 9008