apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupsuser-deployment
  labels:
    app: groupsuser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: groupsuser
  template:
    metadata:
      labels:
        app: groupsuser
    spec:
      containers:
      - name: groupsuser
        image: khalilmilan91/mgroupe_user:s2
        ports:
        - containerPort: 9020
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: GROUPS_USER_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: groupsuser
spec:
  selector:
    app: groupsuser
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 9020