apiVersion: apps/v1
kind: Deployment
metadata:
  name: discussions-deployment
  labels:
    app: discussions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discussions
  template:
    metadata:
      labels:
        app: discussions
    spec:
      containers:
      - name: discussions
        image: khalilmilan91/mdiscussion:s2
        ports:
        - containerPort: 9023
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: DISCUSSIONS_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: discussions
spec:
  selector:
    app: discussions
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9023
      targetPort: 9023