apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
  labels:
    app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: khalilmilan91/mevent:s2
        ports:
        - containerPort: 9001
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: domus-configmap
              key: EVENTS_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: domus-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  selector:
    app: events
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001